/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 
 *
 * OpenAPI spec version: 3.38.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.brightbankdemo.weavr.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * BasicBeneficiary
 */

public class BasicBeneficiary {
  @JsonProperty("beneficiaryDetails")
  private Object beneficiaryDetails = null;

  @JsonProperty("trustLevel")
  private String trustLevel = null;

  @JsonProperty("beneficiaryInformation")
  private Object beneficiaryInformation = null;

  @JsonProperty("group")
  private String group = null;

  public BasicBeneficiary beneficiaryDetails(Object beneficiaryDetails) {
    this.beneficiaryDetails = beneficiaryDetails;
    return this;
  }

   /**
   * The object representing the beneficiary instrument details.
   * @return beneficiaryDetails
  **/
  public Object getBeneficiaryDetails() {
    return beneficiaryDetails;
  }

  public void setBeneficiaryDetails(Object beneficiaryDetails) {
    this.beneficiaryDetails = beneficiaryDetails;
  }

  public BasicBeneficiary trustLevel(String trustLevel) {
    this.trustLevel = trustLevel;
    return this;
  }

   /**
   * Get trustLevel
   * @return trustLevel
  **/
  public String getTrustLevel() {
    return trustLevel;
  }

  public void setTrustLevel(String trustLevel) {
    this.trustLevel = trustLevel;
  }

  public BasicBeneficiary beneficiaryInformation(Object beneficiaryInformation) {
    this.beneficiaryInformation = beneficiaryInformation;
    return this;
  }

   /**
   * The object representing the beneficiary details.
   * @return beneficiaryInformation
  **/
  public Object getBeneficiaryInformation() {
    return beneficiaryInformation;
  }

  public void setBeneficiaryInformation(Object beneficiaryInformation) {
    this.beneficiaryInformation = beneficiaryInformation;
  }

  public BasicBeneficiary group(String group) {
    this.group = group;
    return this;
  }

   /**
   * A custom field that can be used to categorise a beneficiary for easier searching and filtering.
   * @return group
  **/
  public String getGroup() {
    return group;
  }

  public void setGroup(String group) {
    this.group = group;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BasicBeneficiary BasicBeneficiary = (BasicBeneficiary) o;
    return Objects.equals(this.beneficiaryDetails, BasicBeneficiary.beneficiaryDetails) &&
        Objects.equals(this.trustLevel, BasicBeneficiary.trustLevel) &&
        Objects.equals(this.beneficiaryInformation, BasicBeneficiary.beneficiaryInformation) &&
        Objects.equals(this.group, BasicBeneficiary.group);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beneficiaryDetails, trustLevel, beneficiaryInformation, group);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BasicBeneficiary {\n");
    
    sb.append("    beneficiaryDetails: ").append(toIndentedString(beneficiaryDetails)).append("\n");
    sb.append("    trustLevel: ").append(toIndentedString(trustLevel)).append("\n");
    sb.append("    beneficiaryInformation: ").append(toIndentedString(beneficiaryInformation)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
