/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 
 *
 * OpenAPI spec version: 3.38.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.brightbankdemo.weavr.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
/**
 * ManagedAccountsGetResponse
 */

public class ManagedAccountsGetResponse {
  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("responseCount")
  private Integer responseCount = null;

  @JsonProperty("accounts")
  private List<ManagedAccount> accounts = null;

  public ManagedAccountsGetResponse count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public ManagedAccountsGetResponse responseCount(Integer responseCount) {
    this.responseCount = responseCount;
    return this;
  }

   /**
   * Get responseCount
   * @return responseCount
  **/
  public Integer getResponseCount() {
    return responseCount;
  }

  public void setResponseCount(Integer responseCount) {
    this.responseCount = responseCount;
  }

  public ManagedAccountsGetResponse accounts(List<ManagedAccount> accounts) {
    this.accounts = accounts;
    return this;
  }

  public ManagedAccountsGetResponse addAccountsItem(ManagedAccount accountsItem) {
    if (this.accounts == null) {
      this.accounts = new ArrayList<>();
    }
    this.accounts.add(accountsItem);
    return this;
  }

   /**
   * Get accounts
   * @return accounts
  **/
  public List<ManagedAccount> getAccounts() {
    return accounts;
  }

  public void setAccounts(List<ManagedAccount> accounts) {
    this.accounts = accounts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManagedAccountsGetResponse ManagedAccountsGetResponse = (ManagedAccountsGetResponse) o;
    return Objects.equals(this.count, ManagedAccountsGetResponse.count) &&
        Objects.equals(this.responseCount, ManagedAccountsGetResponse.responseCount) &&
        Objects.equals(this.accounts, ManagedAccountsGetResponse.accounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, responseCount, accounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManagedAccountsGetResponse {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    responseCount: ").append(toIndentedString(responseCount)).append("\n");
    sb.append("    accounts: ").append(toIndentedString(accounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
