/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 
 *
 * OpenAPI spec version: 3.53.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.brightbankdemo.weavrfundstransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * BeneficiaryBatch
 */

public class BeneficiaryBatch {
  @JsonProperty("operationBatchId")
  private BeneficiaryOperationBatchId operationBatchId = null;

  @JsonProperty("tag")
  private String tag = null;

  @JsonProperty("state")
  private String state = null;

  public BeneficiaryBatch operationBatchId(BeneficiaryOperationBatchId operationBatchId) {
    this.operationBatchId = operationBatchId;
    return this;
  }

   /**
   * Get operationBatchId
   * @return operationBatchId
  **/
  public BeneficiaryOperationBatchId getOperationBatchId() {
    return operationBatchId;
  }

  public void setOperationBatchId(BeneficiaryOperationBatchId operationBatchId) {
    this.operationBatchId = operationBatchId;
  }

  public BeneficiaryBatch tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public BeneficiaryBatch state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeneficiaryBatch BeneficiaryBatch = (BeneficiaryBatch) o;
    return Objects.equals(this.operationBatchId, BeneficiaryBatch.operationBatchId) &&
        Objects.equals(this.tag, BeneficiaryBatch.tag) &&
        Objects.equals(this.state, BeneficiaryBatch.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationBatchId, tag, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeneficiaryBatch {\n");
    
    sb.append("    operationBatchId: ").append(toIndentedString(operationBatchId)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
