/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 
 *
 * OpenAPI spec version: 3.53.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.brightbankdemo.weavrfundstransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * BulksmanagedCardsIdSpendRulesPathParams
 */

public class BulksmanagedCardsIdSpendRulesPathParams {
  @JsonProperty("_id_")
  private String _id_ = null;

  public BulksmanagedCardsIdSpendRulesPathParams _id_(String _id_) {
    this._id_ = _id_;
    return this;
  }

   /**
   * Get _id_
   * @return _id_
  **/
  public String getId_() {
    return _id_;
  }

  public void setId_(String _id_) {
    this._id_ = _id_;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulksmanagedCardsIdSpendRulesPathParams bulksmanaged_cards_id_spend_rules_pathParams = (BulksmanagedCardsIdSpendRulesPathParams) o;
    return Objects.equals(this._id_, bulksmanaged_cards_id_spend_rules_pathParams._id_);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id_);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulksmanagedCardsIdSpendRulesPathParams {\n");
    
    sb.append("    _id_: ").append(toIndentedString(_id_)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
