/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 
 *
 * OpenAPI spec version: 3.53.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.brightbankdemo.weavrfundstransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
/**
 * BulkProcessOperationsPaged
 */

public class BulkProcessOperationsPaged {
  @JsonProperty("operations")
  private List<BulkProcessOperation> operations = null;

  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("responseCount")
  private Integer responseCount = null;

  public BulkProcessOperationsPaged operations(List<BulkProcessOperation> operations) {
    this.operations = operations;
    return this;
  }

  public BulkProcessOperationsPaged addOperationsItem(BulkProcessOperation operationsItem) {
    if (this.operations == null) {
      this.operations = new ArrayList<>();
    }
    this.operations.add(operationsItem);
    return this;
  }

   /**
   * Get operations
   * @return operations
  **/
  public List<BulkProcessOperation> getOperations() {
    return operations;
  }

  public void setOperations(List<BulkProcessOperation> operations) {
    this.operations = operations;
  }

  public BulkProcessOperationsPaged count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Total number of records (excluding limit)
   * @return count
  **/
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public BulkProcessOperationsPaged responseCount(Integer responseCount) {
    this.responseCount = responseCount;
    return this;
  }

   /**
   * Total number of records returned in this response
   * @return responseCount
  **/
  public Integer getResponseCount() {
    return responseCount;
  }

  public void setResponseCount(Integer responseCount) {
    this.responseCount = responseCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkProcessOperationsPaged BulkProcessOperationsPaged = (BulkProcessOperationsPaged) o;
    return Objects.equals(this.operations, BulkProcessOperationsPaged.operations) &&
        Objects.equals(this.count, BulkProcessOperationsPaged.count) &&
        Objects.equals(this.responseCount, BulkProcessOperationsPaged.responseCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operations, count, responseCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkProcessOperationsPaged {\n");
    
    sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    responseCount: ").append(toIndentedString(responseCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
