/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 
 *
 * OpenAPI spec version: 3.53.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.brightbankdemo.weavrfundstransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * BulksOutgoingWireTransfersBody
 */

public class BulksOutgoingWireTransfersBody {
  @JsonProperty("pathParams")
  private Object pathParams = null;

  @JsonProperty("requestBody")
  private OutgoingWireTransferCreateRequest requestBody = null;

  public BulksOutgoingWireTransfersBody pathParams(Object pathParams) {
    this.pathParams = pathParams;
    return this;
  }

   /**
   * Get pathParams
   * @return pathParams
  **/
  public Object getPathParams() {
    return pathParams;
  }

  public void setPathParams(Object pathParams) {
    this.pathParams = pathParams;
  }

  public BulksOutgoingWireTransfersBody requestBody(OutgoingWireTransferCreateRequest requestBody) {
    this.requestBody = requestBody;
    return this;
  }

   /**
   * Get requestBody
   * @return requestBody
  **/
  public OutgoingWireTransferCreateRequest getRequestBody() {
    return requestBody;
  }

  public void setRequestBody(OutgoingWireTransferCreateRequest requestBody) {
    this.requestBody = requestBody;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulksOutgoingWireTransfersBody bulks_outgoing_wire_transfers_body = (BulksOutgoingWireTransfersBody) o;
    return Objects.equals(this.pathParams, bulks_outgoing_wire_transfers_body.pathParams) &&
        Objects.equals(this.requestBody, bulks_outgoing_wire_transfers_body.requestBody);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pathParams, requestBody);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulksOutgoingWireTransfersBody {\n");
    
    sb.append("    pathParams: ").append(toIndentedString(pathParams)).append("\n");
    sb.append("    requestBody: ").append(toIndentedString(requestBody)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
