/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 
 *
 * OpenAPI spec version: 3.53.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.brightbankdemo.weavrfundstransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
/**
 * BulkProcessesPaged
 */

public class BulkProcessesPaged {
  @JsonProperty("bulk_processes")
  private List<BulkProcess> bulk_processes = null;

  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("responseCount")
  private Integer responseCount = null;

  public BulkProcessesPaged bulk_processes(List<BulkProcess> bulk_processes) {
    this.bulk_processes = bulk_processes;
    return this;
  }

  public BulkProcessesPaged addBulkProcessesItem(BulkProcess bulk_processesItem) {
    if (this.bulk_processes == null) {
      this.bulk_processes = new ArrayList<>();
    }
    this.bulk_processes.add(bulk_processesItem);
    return this;
  }

   /**
   * Get bulk_processes
   * @return bulk_processes
  **/
  public List<BulkProcess> getBulkProcesses() {
    return bulk_processes;
  }

  public void setBulkProcesses(List<BulkProcess> bulk_processes) {
    this.bulk_processes = bulk_processes;
  }

  public BulkProcessesPaged count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Total number of records (excluding limit)
   * @return count
  **/
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public BulkProcessesPaged responseCount(Integer responseCount) {
    this.responseCount = responseCount;
    return this;
  }

   /**
   * Total number of records returned in this response
   * @return responseCount
  **/
  public Integer getResponseCount() {
    return responseCount;
  }

  public void setResponseCount(Integer responseCount) {
    this.responseCount = responseCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkProcessesPaged BulkProcessesPaged = (BulkProcessesPaged) o;
    return Objects.equals(this.bulk_processes, BulkProcessesPaged.bulk_processes) &&
        Objects.equals(this.count, BulkProcessesPaged.count) &&
        Objects.equals(this.responseCount, BulkProcessesPaged.responseCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulk_processes, count, responseCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkProcessesPaged {\n");
    
    sb.append("    bulk_processes: ").append(toIndentedString(bulk_processes)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    responseCount: ").append(toIndentedString(responseCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
