/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 
 *
 * OpenAPI spec version: 3.53.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.brightbankdemo.weavrfundstransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * Send
 */

public class Send {
  @JsonProperty("scheduledTimestamp")
  private String scheduledTimestamp = null;

  @JsonProperty("cancellationReason")
  private String cancellationReason = null;

  @JsonProperty("sourceFee")
  private Object sourceFee = null;

  @JsonProperty("destination")
  private Object destination = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("source")
  private InstrumentId source = null;

  @JsonProperty("destinationFee")
  private Object destinationFee = null;

  @JsonProperty("profileId")
  private String profileId = null;

  @JsonProperty("transactionAmount")
  private Object transactionAmount = null;

  @JsonProperty("creationTimestamp")
  private Long creationTimestamp = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("tag")
  private String tag = null;

  @JsonProperty("state")
  private String state = null;

  @JsonProperty("challengeExemptionReason")
  private String challengeExemptionReason = null;

  @JsonProperty("destinationAmount")
  private CurrencyAmount destinationAmount = null;

  @JsonProperty("executionTimestamp")
  private String executionTimestamp = null;

  public Send scheduledTimestamp(String scheduledTimestamp) {
    this.scheduledTimestamp = scheduledTimestamp;
    return this;
  }

   /**
   * Get scheduledTimestamp
   * @return scheduledTimestamp
  **/
  public String getScheduledTimestamp() {
    return scheduledTimestamp;
  }

  public void setScheduledTimestamp(String scheduledTimestamp) {
    this.scheduledTimestamp = scheduledTimestamp;
  }

  public Send cancellationReason(String cancellationReason) {
    this.cancellationReason = cancellationReason;
    return this;
  }

   /**
   * Get cancellationReason
   * @return cancellationReason
  **/
  public String getCancellationReason() {
    return cancellationReason;
  }

  public void setCancellationReason(String cancellationReason) {
    this.cancellationReason = cancellationReason;
  }

  public Send sourceFee(Object sourceFee) {
    this.sourceFee = sourceFee;
    return this;
  }

   /**
   * Get sourceFee
   * @return sourceFee
  **/
  public Object getSourceFee() {
    return sourceFee;
  }

  public void setSourceFee(Object sourceFee) {
    this.sourceFee = sourceFee;
  }

  public Send destination(Object destination) {
    this.destination = destination;
    return this;
  }

   /**
   * The destination managed account or card to where the funds were sent.
   * @return destination
  **/
  public Object getDestination() {
    return destination;
  }

  public void setDestination(Object destination) {
    this.destination = destination;
  }

  public Send description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description details that are passed to the beneficiary.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Send source(InstrumentId source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  public InstrumentId getSource() {
    return source;
  }

  public void setSource(InstrumentId source) {
    this.source = source;
  }

  public Send destinationFee(Object destinationFee) {
    this.destinationFee = destinationFee;
    return this;
  }

   /**
   * Get destinationFee
   * @return destinationFee
  **/
  public Object getDestinationFee() {
    return destinationFee;
  }

  public void setDestinationFee(Object destinationFee) {
    this.destinationFee = destinationFee;
  }

  public Send profileId(String profileId) {
    this.profileId = profileId;
    return this;
  }

   /**
   * Get profileId
   * @return profileId
  **/
  public String getProfileId() {
    return profileId;
  }

  public void setProfileId(String profileId) {
    this.profileId = profileId;
  }

  public Send transactionAmount(Object transactionAmount) {
    this.transactionAmount = transactionAmount;
    return this;
  }

   /**
   * Get transactionAmount
   * @return transactionAmount
  **/
  public Object getTransactionAmount() {
    return transactionAmount;
  }

  public void setTransactionAmount(Object transactionAmount) {
    this.transactionAmount = transactionAmount;
  }

  public Send creationTimestamp(Long creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
    return this;
  }

   /**
   * The time when the transaction was created, expressed in Epoch timestamp using millisecond precision.
   * @return creationTimestamp
  **/
  public Long getCreationTimestamp() {
    return creationTimestamp;
  }

  public void setCreationTimestamp(Long creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
  }

  public Send id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier of a send transaction.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Send tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public Send state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public Send challengeExemptionReason(String challengeExemptionReason) {
    this.challengeExemptionReason = challengeExemptionReason;
    return this;
  }

   /**
   * Get challengeExemptionReason
   * @return challengeExemptionReason
  **/
  public String getChallengeExemptionReason() {
    return challengeExemptionReason;
  }

  public void setChallengeExemptionReason(String challengeExemptionReason) {
    this.challengeExemptionReason = challengeExemptionReason;
  }

  public Send destinationAmount(CurrencyAmount destinationAmount) {
    this.destinationAmount = destinationAmount;
    return this;
  }

   /**
   * Get destinationAmount
   * @return destinationAmount
  **/
  public CurrencyAmount getDestinationAmount() {
    return destinationAmount;
  }

  public void setDestinationAmount(CurrencyAmount destinationAmount) {
    this.destinationAmount = destinationAmount;
  }

  public Send executionTimestamp(String executionTimestamp) {
    this.executionTimestamp = executionTimestamp;
    return this;
  }

   /**
   * Get executionTimestamp
   * @return executionTimestamp
  **/
  public String getExecutionTimestamp() {
    return executionTimestamp;
  }

  public void setExecutionTimestamp(String executionTimestamp) {
    this.executionTimestamp = executionTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Send Send = (Send) o;
    return Objects.equals(this.scheduledTimestamp, Send.scheduledTimestamp) &&
        Objects.equals(this.cancellationReason, Send.cancellationReason) &&
        Objects.equals(this.sourceFee, Send.sourceFee) &&
        Objects.equals(this.destination, Send.destination) &&
        Objects.equals(this.description, Send.description) &&
        Objects.equals(this.source, Send.source) &&
        Objects.equals(this.destinationFee, Send.destinationFee) &&
        Objects.equals(this.profileId, Send.profileId) &&
        Objects.equals(this.transactionAmount, Send.transactionAmount) &&
        Objects.equals(this.creationTimestamp, Send.creationTimestamp) &&
        Objects.equals(this.id, Send.id) &&
        Objects.equals(this.tag, Send.tag) &&
        Objects.equals(this.state, Send.state) &&
        Objects.equals(this.challengeExemptionReason, Send.challengeExemptionReason) &&
        Objects.equals(this.destinationAmount, Send.destinationAmount) &&
        Objects.equals(this.executionTimestamp, Send.executionTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scheduledTimestamp, cancellationReason, sourceFee, destination, description, source, destinationFee, profileId, transactionAmount, creationTimestamp, id, tag, state, challengeExemptionReason, destinationAmount, executionTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Send {\n");
    
    sb.append("    scheduledTimestamp: ").append(toIndentedString(scheduledTimestamp)).append("\n");
    sb.append("    cancellationReason: ").append(toIndentedString(cancellationReason)).append("\n");
    sb.append("    sourceFee: ").append(toIndentedString(sourceFee)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    destinationFee: ").append(toIndentedString(destinationFee)).append("\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    transactionAmount: ").append(toIndentedString(transactionAmount)).append("\n");
    sb.append("    creationTimestamp: ").append(toIndentedString(creationTimestamp)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    challengeExemptionReason: ").append(toIndentedString(challengeExemptionReason)).append("\n");
    sb.append("    destinationAmount: ").append(toIndentedString(destinationAmount)).append("\n");
    sb.append("    executionTimestamp: ").append(toIndentedString(executionTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
